package com.example.client;

import com.example.service.Todo;
import com.example.service.TodoService;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import java.net.URL;
import java.util.List;

public class Client {
	
	public static void main(String[] args) throws Exception {
		                     //http://localhost:8080/todo-service/TodoService?wsdl
        URL wsdlURL = new URL("http://localhost:8080/todo-service/TodoService?wsdl");
        QName qname = new QName("http://service.example.com/", "TodoService");

        Service service = Service.create(wsdlURL, qname);
        TodoService todoService = service.getPort(TodoService.class);

        todoService.addTodo(new Todo(1, "Write SOAP service"));
        todoService.addTodo(new Todo(2, "Test client"));

        List<Todo> todos = todoService.getTodos();
        for (Todo t : todos) {
            System.out.println(t.getId() + ": " + t.getTask());
        }
    }

}
/*
package com.example.client;

import jakarta.xml.ws.Service;
import javax.xml.namespace.QName;
import java.net.URI;
import java.net.URL;

public class TodoServiceClient {
    public static void main(String[] args) throws Exception {
        // Create URL from URI
        URI wsdlURI = new URI("http://localhost:8080/todo-service/TodoService?wsdl");
        URL wsdlURL = wsdlURI.toURL();
        
        // Service QName (adjust namespace and service name based on WSDL)
        QName serviceName = new QName("http://example.com/todoservice", "TodoService");
        
        // Create Service
        Service service = Service.create(wsdlURL, serviceName);
        
        // Get port (interface generated by wsimport)
        TodoServicePortType port = service.getPort(TodoServicePortType.class);
        
        // Call service method
        String result = port.sayHello("User");
        System.out.println("Response: " + result);
    }
}

// Example interface (generated by wsimport)
interface TodoServicePortType {
    String sayHello(String name);
}
*/
